# Generated by Django 5.0.4 on 2024-07-11 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('meter_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.meterpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=10)),
                ('data_flow_file', models.CharField(max_length=20)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.meter')),
            ],
        ),
    ]
