# Generated by Django 4.2.16 on 2024-10-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='filename',
            new_name='flow_file',
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='app.meterpoint'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meterpoint',
            name='mpan',
            field=models.CharField(max_length=21, unique=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='app.meter'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('meter', 'date')},
        ),
    ]
